"""add_sf_domain_to_apporg

Revision ID: 2a57d90131b7
Revises: bb527a942f17
Create Date: 2025-08-12 13:41:52.488475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a57d90131b7'
down_revision: Union[str, None] = 'bb527a942f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apporg', sa.Column('sf_domain', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apporg', 'sf_domain')
    # ### end Alembic commands ###
