"""add_salesforce_field_mapping_table

Revision ID: 59dd0c146ae1
Revises: 2a57d90131b7
Create Date: 2025-08-13 01:45:26.014466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59dd0c146ae1'
down_revision: Union[str, None] = '2a57d90131b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salesforcefieldmapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('carrier_field', sa.String(), nullable=False),
    sa.Column('salesforce_field', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=True),
    sa.Column('field_type', sa.String(), nullable=False, default='text'),
    sa.ForeignKeyConstraint(['org_id'], ['apporg.org_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salesforcefieldmapping')
    # ### end Alembic commands ###
