"""add_team_request_table

Revision ID: eb01b8dd0869
Revises: 59dd0c146ae1
Create Date: 2025-08-15 21:19:42.411692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb01b8dd0869'
down_revision: Union[str, None] = '59dd0c146ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teamrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('company_size', sa.String(), nullable=True),
    sa.Column('primary_contact_name', sa.String(), nullable=False),
    sa.Column('primary_contact_email', sa.String(), nullable=False),
    sa.Column('primary_contact_phone', sa.String(), nullable=True),
    sa.Column('team_members', sa.JSON(), nullable=True),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teamrequest')
    # ### end Alembic commands ###
